### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 64, 40] to have 4 channels, but got 8 channels instead

### ISSUE THREAD

**Issue by maibacn** [kijai/ComfyUI-IC-Light#51]
I Keep getting this error when using IC-Light, even in example workflow. 

  File "G:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 50, in forward_timestep_embed
    x = layer(x)
        ^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 102, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 64, 40] to have 4 channels, but got 8 channels instead

Please Help

**Comment by gtbloody** [comment]
me too！

**Comment by SuperKen1993** [comment]
Also experiencing this

!!! Exception during processing !!! Given groups=1, weight of size [320, 4, 3, 3], expected input[16, 12, 90, 160] to have 4 channels, but got 12 channels instead
Traceback (most recent call last):
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 526, in motion_sample
    latents = orig_comfy_sample(model, noise, *args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 116, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\k_diffusion\sampling.py", line 653, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 635, in evolved_sampling_function
    cond_pred, uncond_pred = sliding_calc_conds_batch(model, [cond, uncond_], x, timestep, model_options)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 887, in sliding_calc_conds_batch
    sub_conds_out = calc_conds_batch_wrapper(model, sub_conds, sub_x, sub_timestep, model_options)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 993, in calc_conds_batch_wrapper
    return comfy.samplers.calc_cond_batch(model, conds, x_in, timestep, model_options)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 68, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 852, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 172, in forward_timestep_embed
    x = layer(x)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\comfy\ops.py", line 102, in forward
    return super().forward(*args, **kwargs)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\StabilityMatrix\Packages\ComfyUI-ICLight\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[16, 12, 90, 160] to have 4 channels, but got 12 channels instead

**Comment by dapa5900** [comment]
same here since today. was still working last week or so.

**Comment by kijai** [comment]
This was broken by [this ](https://github.com/comfyanonymous/ComfyUI/commit/c26ca272076262c8b21a8f2e094cf538d88b9e46) ComfyUI commit, should be fixed now.

**Comment by lasersees** [comment]
i still facing this error i have updated comfy ui and nodes "Error occurred when executing KSampler:

Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 8, 104, 152] to have 4 channels, but got 8 channels instead

File "C:\Users\biswa\pinokio\api\comfyui.git\app\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\biswa\pinokio\api\comfyui.git\app\nodes.py", line 1382, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\nodes.py", line 1352, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
File "C:\Users\biswa\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
raise e
File "C:\Users\biswa\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\sample.py", line 43, in sample
samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 829, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 729, in sample
return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 716, in sample
output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 695, in inner_sample
samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 600, in sample
samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\k_diffusion\sampling.py", line 600, in sample_dpmpp_2m
denoised = model(x, sigmas[i] * s_in, **extra_args)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 299, in __call__
out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 682, in __call__
return self.predict_noise(*args, **kwargs)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 685, in predict_noise
return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 279, in sampling_function
out = calc_cond_batch(model, conds, x, timestep, model_options)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 4, in calc_cond_batch
return calc_cond_batch_original_tiled_diffusion_ca60f944(model, conds, x_in, timestep, model_options)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\samplers.py", line 226, in calc_cond_batch
output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-IC-Light-Native\ic_light_nodes.py", line 116, in wrapper_func
return existing_wrapper(unet_apply, params=apply_c_concat(params))
File "C:\Users\biswa\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-IC-Light-Native\ic_light_nodes.py", line 108, in unet_dummy_apply
return unet_apply(x=params["input"], t=params["timestep"], **params["c"])
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\model_base.py", line 122, in apply_model
model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
File "C:\Users\biswa\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 852, in forward
h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 50, in forward_timestep_embed
x = layer(x)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\comfy\ops.py", line 93, in forward
return super().forward(*args, **kwargs)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
return self._conv_forward(input, self.weight, self.bias)
File "C:\Users\biswa\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,"

**Comment by kijai** [comment]
Make sure the nodes are actually updated, I don't see any other reason for it to still give the same error.

**Comment by gtbloody** [comment]
> This was broken by [this ](https://github.com/comfyanonymous/ComfyUI/commit/c26ca272076262c8b21a8f2e094cf538d88b9e46) ComfyUI commit, should be fixed now.

fixed！

**Comment by yincangshiwei** [comment]
I also have this problem, has it been fixed?

**Comment by Yanquansu** [comment]
same issue!!!

Error occurred when executing KSampler (Efficient):

Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 72] to have 4 channels, but got 8 channels instead

File "C:\Users\Steve\AI\Comfyui\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "C:\Users\Steve\AI\Comfyui\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 732, in sample
samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 550, in process_latent_image
samples = KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\nodes.py", line 1429, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\nodes.py", line 1396, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
raise e
File "C:\Users\Steve\AI\Comfyui\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py", line 116, in acn_sample
return orig_comfy_sample(model, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 116, in uncond_multiplier_check_cn_sample
return orig_comfy_sample(model, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\sample.py", line 43, in sample
samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 829, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 729, in sample
return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 716, in sample
output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 695, in inner_sample
samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 600, in sample
samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\k_diffusion\sampling.py", line 144, in sample_euler
denoised = model(x, sigma_hat * s_in, **extra_args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 299, in __call__
out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 682, in __call__
return self.predict_noise(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 685, in predict_noise
return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 279, in sampling_function
out = calc_cond_batch(model, conds, x, timestep, model_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 4, in calc_cond_batch
return calc_cond_batch_original_tiled_diffusion_526a6045(model, conds, x_in, timestep, model_options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\samplers.py", line 228, in calc_cond_batch
output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 68, in apply_model_uncond_cleanup_wrapper
return orig_apply_model(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\model_base.py", line 142, in apply_model
model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 852, in forward
h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 50, in forward_timestep_embed
x = layer(x)
^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\comfy\ops.py", line 106, in forward
return super().forward(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\venv\Lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
return self._conv_forward(input, self.weight, self.bias)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Steve\AI\Comfyui\venv\Lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,

**Comment by kijai** [comment]
> I also have this problem, has it been fixed? And even though I updated the latest version of ComfyUI today, I still have this issue.

Yes it's been fixed, update both ComfyUI and these nodes.

**Comment by kijai** [comment]
> same issue!!!

Update.

**Comment by Yanquansu** [comment]
hello! Your letter I have received, thanks!

**Comment by alexnikospb** [comment]
Hi! Updated Comfy and all nodes, problem persists.

**Comment by kijai** [comment]
> Hi! Updated Comfy and all nodes, problem persists.

Make sure it's actually updated, many have said same but then it turned out their Comfy or the nodes weren't actually updated.

**Comment by alexnikospb** [comment]
> > Hi! Updated Comfy and all nodes, problem persists.
> 
> Make sure it's actually updated, many have said same but then it turned out their Comfy or the nodes weren't actually updated.

checked: "ComfyUI and all extensions are already up-to-date with the latest versions"

![Uploading IMG_20240825_144457.jpg…]()

**Comment by kijai** [comment]
> > > Hi! Updated Comfy and all nodes, problem persists.
> > 
> > 
> > Make sure it's actually updated, many have said same but then it turned out their Comfy or the nodes weren't actually updated.
> 
> checked: "ComfyUI and all extensions are already up-to-date with the latest versions"

If you are sure, then you are either using wrong model, or it's reporting that it's updated mistakenly, because this 100% works with the latest versions.

**Comment by Guolker** [comment]
Same problem here, Comfyui and custom nodes updated. 1.5 model used:
"RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 309, 240] to have 4 channels, but got 8 channels instead"

**Comment by lihaotw** [comment]
I'm experiencing the same error issue. I've carefully double-checked that ComfyUI and all extensions are updated to the latest versions. I'm using the default workflow and models, but the problem still persists. Could there be any other factors I'm overlooking? I'd appreciate any additional suggestions or troubleshooting steps.

**Comment by kijai** [comment]
Try updating the nodes now, I removed the backwards compatibility in case that's causing issues. Tested on current latest ComfyUI version.

**Comment by alexnikospb** [comment]
> Try updating the nodes now, I removed the backwards compatibility in case that's causing issues. Tested on current latest ComfyUI version.

Yes, it works!

**Comment by Yanquansu** [comment]
> Try updating the nodes now, I removed the backwards compatibility in case that's causing issues. Tested on current latest ComfyUI version.

it works after reinstalll IC-Light , thank you so much.

**Comment by Guolker** [comment]
> Try updating the nodes now, I removed the backwards compatibility in case that's causing issues. Tested on current latest ComfyUI version.

Working perfectly now, thanks a lot...!!

**Comment by anyi-suchuyin** [comment]
I also ran into this issue and later used this model to solve this problem：https://huggingface.co/huchenlei/IC-Light-ldm/tree/main

**Comment by ivans80** [comment]
I got this Error on Ksampler node and solve it with change sheduler from normal to karras

**Comment by lucabaronti** [comment]
Having this exact error using one of the [example workflows](https://github.com/kijai/ComfyUI-IC-Light/blob/main/examples/iclight_example_fc_controlled_gradient_01.png). Scheduler is set to kerras and also switching to this model don't solve the issue https://huggingface.co/huchenlei/IC-Light-ldm/tree/main
